FROM jetbrains/teamcity-agent:2017.1.1

# Install dotnet
RUN sudo apt-get update \ 
&&  sudo apt-get install apt-transport-https \
&&  sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' \
&&  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893 \                                                                    
&&  sudo apt-get update \
&&  sudo apt-get install -y dotnet-dev-1.0.3 \
&&  sudo apt-get remove -y apt-transport-https \
&&  rm -rf /var/lib/apt/lists/*